apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-example
  labels:
    app: examples
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examples
  template:
    metadata:
      labels:
        app: examples
    spec:
      containers:
      - name: node-example
        image: aksczacr.azurecr.io/node-example:latest
        ports:
        - containerPort: 3000